clients/CMakeLists.txt, clients/shell.c, clients/shell.h, clients/shell_bg.c, clients/shell_bus.c, clients/shell_msgs.c, clients/shell_panel.c, clients/shell_ui.c, clients/widget.h, server/desktop/shell.c, shared_config.h
adding notification and menu widget.
=> WIP:Notify menu

clients/console.c, clients/console_module/console_app.c, clients/console_module/console_cmd.c, clients/console_module/console_module.c, clients/console_module/console_module.h, clients/console_module/console_path.c, docs/progress.org, server/desktop/console.c, server/main.c
- TODO: fix missing cursor after remove
- TODO: implement console search navigate
=> WIP: console update

clients/console.c, clients/console_module/console_app.c, clients/console_module/console_cmd.c, clients/console_module/console_module.c, clients/console_module/console_module.h, clients/update_icon_cache.c, docs/progress.org
- loading icons in console(doesn't look pretty either)
- load app.cache for only in desktop_entries
=> Console icon

meson.build
=> meson: add option to build a built-in pixman for memory sanitizer.

server/backend/backend.c, server/backend/backend.h, server/backend/backend_output.c, server/backend/backend_seat.c, server/desktop/layout.c, server/desktop/layout.h, server/desktop/layout_floating.c, server/desktop/layout_fullscreen.c, server/desktop/layout_maximized.c, server/desktop/layout_tiling.c, server/desktop/workspace.c, server/desktop/workspace.h, server/desktop/xdg.c, server/desktop/xdg.h, server/desktop/xdg_grab.c, server/desktop/xdg_internal.h, server/meson.build, server/objects/desktop.h, server/objects/desktop_xdg_shell.c, server/objects/layers.h, server/objects/utils.c, server/objects/utils.h, server/taiwins.h
=> finish the desktop objects.

server/backend/backend.c, server/backend/backend_output.c, server/include/backend.h, server/include/taiwins/objects/presentation_feedback.h, server/meson.build, server/objects/presentation_feedback.c, server/renderer/layer_renderer.c
=> presentation_feedback: adding presentation_feedback protocols

server/backend/backend.c, server/backend/backend_seat.c, server/desktop/xdg_grab.c, server/include/backend.h, server/include/taiwins/objects/cursor.h, server/include/taiwins/objects/surface.h, server/objects/cursor.c, server/objects/surface.c
=> Input region fix

server/desktop/layout.h, server/desktop/layout_tiling.c, server/desktop/workspace.c, server/desktop/xdg.c
=> Fix tiling new surface

server/backend/backend_seat.c, server/desktop/workspace.c, server/desktop/workspace.h, server/desktop/xdg.c, server/include/taiwins/objects/data_device.h, server/include/taiwins/objects/desktop.h, server/include/taiwins/objects/popup_grab.h, server/include/taiwins/objects/seat.h, server/include/taiwins/objects/utils.h, server/objects/cursor.c, server/objects/data_device/data_device.c, server/objects/data_device/data_dnd.c, server/objects/data_device/data_offer.c, server/objects/data_device/data_source.c, server/objects/desktop/desktop.c, server/objects/desktop/desktop_wl_shell.c, server/objects/desktop/desktop_xdg_shell.c, server/objects/popup_grab.c, server/objects/seat/seat.c, server/objects/seat/seat_keyboard.c, server/objects/seat/seat_pointer.c, server/objects/seat/seat_touch.c, server/objects/utils.c, server/renderer/layer_renderer.c
=> data_device: fix data_device copy paste issue.

meson_options.txt, server/backend/backend.c, server/backend/backend_impl.c, server/backend/backend_output.c, server/desktop/workspace.c, server/include/backend.h, server/include/taiwins/objects/matrix.h, server/include/taiwins/objects/surface.h, server/meson.build, server/objects/matrix.c, server/objects/subsurface.c, server/objects/surface.c, server/renderer/layer_renderer.c, server/renderer/renderer.c, server/renderer/renderer.h, server/renderer/shaders.c, server/renderer/shaders.h, test/meson.build
The new renderer would be more efficient on updating the output, and possibly supporting different callbacks.
=> Renderer redesign

meson.build, server/backend/backend_impl.c, server/desktop/layout_tiling.c
=> meson: build on release

CONTRIBUTING.md
=> doc:adding issue guideline

libtaiwins/backend/drm/drm-gbm.c, libtaiwins/backend/drm/kms.c
=> drm: implementing legacy pageflip functions.

include/taiwins/output_device.h, libtaiwins/backend/drm/display.c, libtaiwins/output_device.c
=> drm-display: fix display mode update in the commit state event.

include/taiwins/backend_drm.h, include/taiwins/render_context.h, libtaiwins/backend/backend.c, libtaiwins/backend/drm/backend.c, libtaiwins/backend/drm/login/login.c, libtaiwins/backend/headless.c, libtaiwins/backend/wayland/backend.c, libtaiwins/backend/wayland/output.c, libtaiwins/backend/x11/backend.c, libtaiwins/backend/x11/output.c, libtaiwins/desktop/workspace.c, libtaiwins/desktop/xdg.c, libtaiwins/desktop/xdg_grab.c, libtaiwins/engine/engine.c, libtaiwins/engine/output.c, libtaiwins/engine/seat.c, libtaiwins/output_device.c, libtaiwins/render/egl_render_context.c, libtaiwins/render/egl_simple_pipeline.c, libtaiwins/render/render_context.c, libtaiwins/render/render_output.c, libtaiwins/render/render_pipeline.c, libtaiwins/shell/console.c, libtaiwins/shell/shell.c, libtaiwins/shell/theme.c
=> ci: expose symbols

test/test_desktop.c
=> test: adding moving grab to test desktop.

compositor/config/config.c, compositor/config/config.h, compositor/config/config_bindings.c, compositor/config/config_lua.c, compositor/config/config_types.h, compositor/desktop/layout.h, compositor/desktop/layout_floating.c, compositor/desktop/layout_fullscreen.c, compositor/desktop/layout_maximized.c, compositor/desktop/layout_tiling.c, compositor/desktop/workspace.h, compositor/desktop/xdg.c, compositor/desktop/xdg.h, compositor/desktop/xdg_grab.c, compositor/desktop/xdg_grab.h, compositor/main.c
Later we would use this it for binding xwayland_ready_listener.
=> compositor: expose tw_xdg structure.

compositor/egl_renderer.c, libtaiwins/render/render_output.c
=> Fix the renderer damage problem

README.md
=> README: adding badge

compositor/input.c, include/taiwins/render_output.h, libtaiwins/backend/drm/backend.c, libtaiwins/backend/drm/display.c, libtaiwins/backend/drm/internal.h, libtaiwins/backend/drm/login/logind.c, libtaiwins/backend/headless.c, libtaiwins/backend/wayland/output.c, libtaiwins/backend/x11/output.c, libtaiwins/dbus_utils.c, libtaiwins/engine/seat.c, libtaiwins/render/render_output.c
These patches fix the issue we can switch to another session but cannot switch back.
=> logind: getting signals for dbus

libtaiwins/backend/wayland/backend.c, libtaiwins/backend/wayland/internal.h, libtaiwins/backend/wayland/output.c
adding logic to determine starting wl_backend_output.
=> backend-wayland: wl_backend_output_start_maybe

include/taiwins/backend.h, libtaiwins/backend/backend.c, libtaiwins/backend/drm/backend.c, libtaiwins/backend/headless.c, libtaiwins/backend/wayland/backend.c, libtaiwins/backend/x11/backend.c
=> backend: remove backend.destroy signal it is not used

compositor/desktop/layout.h, compositor/desktop/layout_tiling.c, compositor/desktop/workspace.c
=> compositor: correcting view focused state on applying layout

compositor/desktop/xdg.c, test/test_desktop.c
=> desktop: using tw_seat instead wl_resource

include/taiwins/engine.h, libtaiwins/engine/engine.c, libtaiwins/engine/seat.c
=> engine: introducing seat:focused signal in engine

compositor/desktop/layout.c, compositor/desktop/layout.h, compositor/desktop/layout_fullscreen.c, compositor/desktop/layout_maximized.c, compositor/desktop/workspace.c
=> compositor:desktop: resizing output triggers the back layer surface resizing

compositor/config/config.c
=> build: deal with unused xwayland variable if xwayland not available.

docs/config.lua
=> doc: updating the current config.lua example

libtaiwins/backend/drm/drm-gbm.c
Before we can remove visual_id completely, we can try to use XRGB8888 if
argb8888 not available on DRM plane. If both failed, we are doomed.
=> drm: strip alpha channel if DRM_FORMAT_ARGB8888 not available

.gitmodules, protocols/meson.build, protocols/taiwins-console.xml, protocols/taiwins-shell.xml, protocols/taiwins-theme.xml
We still keeps the taiwins protocol repository for official protocol updates.
=> protocols: merge the taiwins protocols here so we kill another submodule

README.md
=> README: correcting links

libtaiwins/objects/data_device/data_offer.c
data_offer_set_actions
We should not just cancel the data_source as we may get multiple actions. The
cancel caused firefox failed to perform the dnd operations.
=> data-device: sending none actions instead of cancel on no matches

include/taiwins/objects/desktop.h, libtaiwins/objects/desktop/desktop.c, libtaiwins/objects/desktop/desktop_wl_shell.c, libtaiwins/objects/desktop/desktop_xdg_shell.c, libtaiwins/xwayland/window.c
=> desktop: using tw_surface instead wl_surface on tw_desktop_surface_init

compositor/input.c, compositor/input.h, compositor/main.c
Making a global input manager.
=> compositor: tw-server-input-manager

compositor/desktop/workspace.c, include/taiwins/objects/desktop.h, libtaiwins/objects/desktop/desktop.c, libtaiwins/objects/desktop/desktop_wl_shell.c, libtaiwins/objects/desktop/desktop_xdg_shell.c, libtaiwins/xwayland/window.c, libtaiwins/xwayland/xwm.c
=> desktop-surface-roles: getting tw_desktop_surface from roles.

compositor/config/config_bindings.c, compositor/desktop/xdg.c, compositor/desktop/xdg_grab.c, compositor/input.c, include/taiwins/objects/seat.h, include/taiwins/objects/seat_grab.h, libtaiwins/engine/seat.c, libtaiwins/objects/data_device/data_device.c, libtaiwins/objects/data_device/data_dnd.c, libtaiwins/objects/popup_grab.c, libtaiwins/objects/seat/seat_keyboard.c, libtaiwins/objects/seat/seat_pointer.c, libtaiwins/objects/seat/seat_touch.c, libtaiwins/shell/console.c, libtaiwins/shell/shell.c, test/test_desktop.c
Preparation work for idle-locker.
=> Seat grab and focus

include/taiwins/input_device.h, include/taiwins/objects/gestures.h, include/taiwins/objects/seat_grab.h
=> input-device: move input events definition into objects

libtaiwins/input_device.c
=> input-device: exposing input-device API as they are exposed in headers
